apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-reactive-app
  labels:
    app: spring-reactive-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-reactive-app
  template:
    metadata:
      labels:
        app: spring-reactive-app
    spec:
      containers:
        - name: spring-reactive-app
          image: juniorreis/spring-reactive-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: reactive-app-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
