apiVersion: v1
kind: Service
metadata:
  name: spring-reactive-app-service
  labels:
    app: spring-reactive-app
spec:
  selector:
    app: spring-reactive-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
